name: Build

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-unknown-linux-gnu
            os: self-hosted

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # - name: Install libzmq3-dev
      #   run: sudo apt install -y libzmq3-dev:arm64

      # - name: Add toolchain
      #   run: rustup toolchain install stable-${{ matrix.target }}

      # - name: Set toolchain
      #   run: rustup default stable-${{ matrix.target }}

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Rustup
        run: rustup show

      # - name: Build
      #   run: cargo build --release --target ${{ matrix.target }}

      # - name: Run binary
      #   run: ./target/${{ matrix.target }}/release/try-actions

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: try-actions-${{ matrix.target }}
      #     path: ./target/${{ matrix.target }}/release/try-actions
