name: Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-release:
    name: Create GitHub release
    # only publish from the origin repository
    if: github.repository_owner == 'victorshevtsov'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - uses: taiki-e/create-gh-release-action@v1
        with:
          branch: master
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: "Upload release assets"
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - uses: taiki-e/upload-rust-binary-action@v1
        id: build-binary
        with:
          bin: try-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: ./target/release/try-actions

  create-docker-image:
    name: "Create Docker image"
    needs: upload-assets
    runs-on: ubuntu-latest
    steps:
      # - name: Check out the repository
      #   uses: actions/checkout@v4

      - name: Download release binaries(ubuntu-latest)
        uses: actions/download-artifact@v4
        with:
          name: binary-ubuntu-latest
          path: binary-amd64

      - name: Download release binaries(macos-latest)
        uses: actions/download-artifact@v4
        with:
          name: binary-macos-latest
          path: binary-arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: 1arp/create-a-file-action@0.4.5
        with:
          # path: 'src'
          # isAbsolutePath: false
          file: 'Dockerfile'
          content: |
            FROM debian:bookworm-slim

            RUN \
              apt update && \
              apt install -y openssl && \
              rm -rf /var/lib/apt/lists/*

            COPY ./binary-$TARGETARCH/try-actions /usr/local/bin/try-actions

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
